spring:
  datasource:
    druid:
      filters: stat,wall,WebStat #开启监控
      aop-patterns: com.gsj.controller.DemoController.*
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: t
        principal-cookie-name: JSESSIONID
        profileEnable: true
        principalSessionName: user
      stat-view-servlet:
        enabled: true
        allow: 127.0.0.1
        deny: 192.168.252.66
        login-username: admin
        login-password: 123456
        reset-enable: true
        url-pattern: /druid/*
    url: jdbc:mysql://localhost:3306/test?rewriteBatchedStatements=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&allowPublicKeyRetrieval=true
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver # 驱动
  jpa:
    hibernate:
      ddl-auto: update # 自动更新
    show-sql: true     #日志中显示sql语句
